import type { ConfigProfile } from '../../domain/entities/config-profile'
import { RISK_PROFILES } from '../../domain/value-objects/risk-profile'
import { COMPLIANCE_FRAMEWORKS } from '../../domain/value-objects/compliance-framework'
import type { GeneratedArtifact } from '../../domain/ports/template-engine-port'

export function generateClaudeMd(profile: ConfigProfile): GeneratedArtifact {
  const risk = RISK_PROFILES[profile.riskProfile]
  const frameworks = profile.complianceFrameworks.map((id) => COMPLIANCE_FRAMEWORKS[id])

  const lines: string[] = [
    `# CLAUDE.md — ${profile.projectName}`,
    `# Generated by ClaudeGuard Security Configurator`,
    `# Organization: ${profile.organizationName}`,
    `# Risk Profile: ${risk.name}`,
    `# Compliance: ${frameworks.map((f) => f.shortName).join(', ')}`,
    ``,
    `## Security Constraints`,
    ``,
    `You are operating in a **${risk.name}** security environment managed by ClaudeGuard.`,
    ``,
  ]

  if (profile.riskProfile === 'paranoid') {
    lines.push(
      `### CRITICAL RESTRICTIONS`,
      `- You have NO internet access. Do not attempt web requests.`,
      `- You have NO MCP server access. Do not attempt MCP connections.`,
      `- The filesystem is READ-ONLY outside of /home/claudecode/workspace.`,
      `- ALL actions are fully audited and logged.`,
      `- Direct Bash execution is DISABLED. All commands go through hooks.`,
      ``,
    )
  } else if (profile.riskProfile === 'strict') {
    lines.push(
      `### Key Restrictions`,
      `- Network egress is restricted to allowlisted domains only.`,
      `- All tool use goes through pre/post execution hooks.`,
      `- Credential patterns in output will be blocked.`,
      `- MCP server connections require explicit approval.`,
      `- Bypass mode is disabled — you cannot override security policies.`,
      ``,
    )
  } else {
    lines.push(
      `### Security Baseline`,
      `- Dangerous commands (rm -rf /, shutdown, etc.) are blocked.`,
      `- File access is scoped to the project directory.`,
      `- Basic audit logging is enabled.`,
      ``,
    )
  }

  lines.push(
    `## Forbidden Patterns`,
    ``,
    `Never generate, output, or store:`,
    `- API keys, secrets, passwords, or tokens in source code`,
    `- Hardcoded credentials of any kind`,
    `- Connection strings with embedded passwords`,
    `- Private keys or certificates`,
    ``,
    `If you encounter credentials in existing code, flag them for remediation.`,
    ``,
  )

  if (frameworks.some((f) => f.id === 'hipaa')) {
    lines.push(
      `## HIPAA Compliance`,
      ``,
      `- Do NOT access, read, or process files containing Protected Health Information (PHI)`,
      `- Paths matching /phi/**, /patient/**, /medical/** are blocked by policy`,
      `- Zero Data Retention (ZDR) is active — no data is stored on Anthropic servers`,
      `- Report any PHI exposure immediately`,
      ``,
    )
  }

  if (frameworks.some((f) => f.id === 'pci-dss')) {
    lines.push(
      `## PCI-DSS Compliance`,
      ``,
      `- Do NOT access files containing cardholder data`,
      `- Paths matching /card/**, /payment/**, /pan/** are blocked by policy`,
      `- Network communication is VPC-contained`,
      `- All database queries must use parameterized statements`,
      ``,
    )
  }

  if (frameworks.some((f) => f.id === 'gdpr')) {
    lines.push(
      `## GDPR Compliance`,
      ``,
      `- Data residency: EU region only`,
      `- Support right-to-erasure in any data handling code`,
      `- Include consent management in any user-facing features`,
      `- Conduct privacy impact assessment for new data processing`,
      ``,
    )
  }

  lines.push(
    `## Coding Standards`,
    ``,
    `- Write secure, defensive code following OWASP Top 10 guidelines`,
    `- Use parameterized queries for all database access`,
    `- Validate and sanitize all user input`,
    `- Use environment variables for configuration — never hardcode`,
    `- Follow the principle of least privilege in all access patterns`,
    `- Include error handling that does not leak sensitive information`,
    ``,
    `## Project Context`,
    ``,
    `This workspace is managed by ClaudeGuard with the following configuration:`,
    `- **Organization**: ${profile.organizationName}`,
    `- **Project**: ${profile.projectName}`,
    `- **Risk Profile**: ${risk.name}`,
    `- **Compliance Frameworks**: ${frameworks.map((f) => f.name).join(', ')}`,
    `- **Cloud Provider**: ${profile.cloudProvider.toUpperCase()}`,
  )

  return {
    filename: 'CLAUDE.md',
    content: lines.join('\n'),
    language: 'markdown',
    description: 'Project-level instructions governing Claude Code behaviour and security constraints',
  }
}
