import type { ConfigProfile } from '../../domain/entities/config-profile'
import { RISK_PROFILES } from '../../domain/value-objects/risk-profile'
import type { GeneratedArtifact } from '../../domain/ports/template-engine-port'

export function generateDockerfile(profile: ConfigProfile): GeneratedArtifact {
  const risk = RISK_PROFILES[profile.riskProfile]
  const isParanoid = profile.riskProfile === 'paranoid'
  const isStrict = profile.riskProfile === 'strict' || isParanoid

  const lines: string[] = [
    `# ClaudeGuard Hardened Claude Code Container`,
    `# Risk Profile: ${risk.name}`,
    `# Generated by ClaudeGuard Security Configurator`,
    ``,
    `FROM node:22-slim AS base`,
    ``,
    `# Security: non-root user`,
    `RUN groupadd -r claudecode && useradd -r -g claudecode -m -s /bin/bash claudecode`,
    ``,
    `# System dependencies`,
    `RUN apt-get update && apt-get install -y --no-install-recommends \\`,
    `    curl \\`,
    `    git \\`,
    `    ca-certificates \\`,
    `    iptables \\`,
    `    dnsutils \\`,
    `    jq \\`,
  ]

  if (!isParanoid) {
    lines.push(
      `    python3 \\`,
      `    python3-pip \\`,
    )
  }

  lines.push(
    `    && rm -rf /var/lib/apt/lists/*`,
    ``,
    `# Install Claude Code CLI`,
    `RUN npm install -g @anthropic-ai/claude-code@latest`,
    ``,
    `# Firewall setup script`,
    `COPY init-firewall.sh /usr/local/bin/init-firewall.sh`,
    `RUN chmod +x /usr/local/bin/init-firewall.sh`,
    ``,
    `# Managed settings (enterprise policy — cannot be overridden)`,
    `RUN mkdir -p /etc/claude-code`,
    `COPY managed-settings.json /etc/claude-code/managed-settings.json`,
    `RUN chmod 444 /etc/claude-code/managed-settings.json`,
    ``,
  )

  if (isStrict) {
    lines.push(
      `# Hook scripts (mandatory for ${risk.name} profile)`,
      `COPY hooks/ /etc/claude-code/hooks/`,
      `RUN chmod +x /etc/claude-code/hooks/*.sh`,
      ``,
    )
  }

  lines.push(
    `# CLAUDE.md project instructions`,
    `COPY CLAUDE.md /home/claudecode/CLAUDE.md`,
    ``,
    `# Working directory`,
    `WORKDIR /home/claudecode/workspace`,
    `RUN chown -R claudecode:claudecode /home/claudecode`,
    ``,
  )

  if (isParanoid) {
    lines.push(
      `# Paranoid: read-only filesystem outside workspace`,
      `RUN chmod -R a-w /usr/local/lib/node_modules || true`,
      ``,
    )
  }

  lines.push(
    `# Resource limits (applied via docker-compose, documented here)`,
    `# CPU: ${isParanoid ? '1 core' : isStrict ? '2 cores' : '4 cores'}`,
    `# Memory: ${isParanoid ? '2GB' : isStrict ? '4GB' : '8GB'}`,
    ``,
    `# Switch to non-root user`,
    `USER claudecode`,
    ``,
    `# Health check`,
    `HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\`,
    `    CMD claude --version || exit 1`,
    ``,
    `# Entrypoint: initialize firewall, then start shell`,
    `ENTRYPOINT ["/usr/local/bin/init-firewall.sh"]`,
    `CMD ["/bin/bash"]`,
  )

  return {
    filename: 'Dockerfile',
    content: lines.join('\n'),
    language: 'dockerfile',
    description: 'Container image definition with security hardening, non-root user, and firewall',
  }
}
