import type { ConfigProfile } from '../../domain/entities/config-profile'
import { RISK_PROFILES } from '../../domain/value-objects/risk-profile'
import { CLOUD_PROVIDERS } from '../../domain/value-objects/cloud-provider'
import type { GeneratedArtifact } from '../../domain/ports/template-engine-port'

export function generateDockerCompose(profile: ConfigProfile): GeneratedArtifact {
  const risk = RISK_PROFILES[profile.riskProfile]
  const cloud = CLOUD_PROVIDERS[profile.cloudProvider]
  const isParanoid = profile.riskProfile === 'paranoid'
  const isStrict = profile.riskProfile === 'strict' || isParanoid

  const cpuLimit = isParanoid ? '1.0' : isStrict ? '2.0' : '4.0'
  const memLimit = isParanoid ? '2g' : isStrict ? '4g' : '8g'

  const envVars: Record<string, string> = {
    CLAUDE_CODE_MANAGED_SETTINGS: '/etc/claude-code/managed-settings.json',
    ANTHROPIC_API_KEY: '${ANTHROPIC_API_KEY}',
  }

  if (isStrict) {
    envVars.CLAUDE_CODE_HOOKS_DIR = '/etc/claude-code/hooks'
  }

  const envBlock = Object.entries(envVars)
    .map(([k, v]) => `      ${k}: ${v}`)
    .join('\n')

  const volumes = [
    './workspace:/home/claudecode/workspace',
    './managed-settings.json:/etc/claude-code/managed-settings.json:ro',
    './CLAUDE.md:/home/claudecode/CLAUDE.md:ro',
  ]

  if (isStrict) {
    volumes.push('./hooks:/etc/claude-code/hooks:ro')
  }

  const volumeBlock = volumes.map((v) => `      - ${v}`).join('\n')

  const networks = isStrict
    ? `    networks:\n      - claude-internal\n      - claude-egress`
    : `    networks:\n      - claude-network`

  const networkDefs = isStrict
    ? `networks:
  claude-internal:
    driver: bridge
    internal: true
  claude-egress:
    driver: bridge`
    : `networks:
  claude-network:
    driver: bridge`

  const content = `# ClaudeGuard Docker Compose Configuration
# Risk Profile: ${risk.name}
# Cloud Provider: ${cloud.name}
# Generated by ClaudeGuard Security Configurator

services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claudeguard-\${PROJECT_NAME:-claude-code}
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true${isParanoid ? '\n    read_only: true' : ''}
    deploy:
      resources:
        limits:
          cpus: '${cpuLimit}'
          memory: ${memLimit}
        reservations:
          cpus: '0.5'
          memory: 512m
    environment:
${envBlock}
    volumes:
${volumeBlock}${isParanoid ? '\n      - tmpfs:/tmp' : ''}
    dns:
      - ${isStrict ? '10.0.0.2  # Corporate DNS only' : '8.8.8.8'}
${networks}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

${networkDefs}
`

  return {
    filename: 'docker-compose.yml',
    content,
    language: 'yaml',
    description: 'Multi-service orchestration with network isolation and resource limits',
  }
}
