import type { ConfigProfile } from '../../domain/entities/config-profile'
import { RISK_PROFILES } from '../../domain/value-objects/risk-profile'
import { CLOUD_PROVIDERS } from '../../domain/value-objects/cloud-provider'
import type { GeneratedArtifact } from '../../domain/ports/template-engine-port'

export function generateFirewall(profile: ConfigProfile): GeneratedArtifact {
  const risk = RISK_PROFILES[profile.riskProfile]
  const cloud = CLOUD_PROVIDERS[profile.cloudProvider]

  const allDomains = new Set<string>([
    ...risk.networkPolicy.allowedDomains.filter((d) => d !== '*'),
    ...cloud.firewallAllowDomains,
  ])

  const allowAll = risk.networkPolicy.allowedDomains.includes('*')

  const lines: string[] = [
    `#!/bin/bash`,
    `# ClaudeGuard Container Firewall`,
    `# Risk Profile: ${risk.name}`,
    `# Cloud Provider: ${cloud.shortName}`,
    `# Generated by ClaudeGuard Security Configurator`,
    ``,
    `set -euo pipefail`,
    ``,
    `echo "[ClaudeGuard] Initializing container firewall..."`,
    ``,
    `# ============================================`,
    `# Network Policy: Default ${risk.networkPolicy.defaultEgress.toUpperCase()} outbound`,
    `# ============================================`,
    ``,
  ]

  if (allowAll) {
    lines.push(
      `# Standard profile: allow all outbound, deny known-dangerous`,
      `iptables -P OUTPUT ACCEPT`,
      ``,
      `# Block known-dangerous destinations`,
      `# (metadata endpoints — prevent SSRF attacks)`,
      `iptables -A OUTPUT -d 169.254.169.254 -j DROP  # AWS metadata`,
      `iptables -A OUTPUT -d 100.100.100.200 -j DROP  # Alibaba metadata`,
      `iptables -A OUTPUT -d metadata.google.internal -j DROP 2>/dev/null || true`,
      ``,
    )
  } else {
    lines.push(
      `# ${risk.name} profile: default DENY outbound`,
      `iptables -P OUTPUT DROP`,
      ``,
      `# Allow loopback`,
      `iptables -A OUTPUT -o lo -j ACCEPT`,
      ``,
      `# Allow established connections`,
      `iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT`,
      ``,
      `# Allow DNS (required for domain resolution)`,
      `iptables -A OUTPUT -p udp --dport 53 -j ACCEPT`,
      `iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT`,
      ``,
      `# ============================================`,
      `# Allowlisted domains`,
      `# ============================================`,
      ``,
    )

    allDomains.forEach((domain) => {
      const cleanDomain = domain.replace(/^\*\./, '')
      lines.push(
        `# ${domain}`,
        `for ip in $(dig +short ${cleanDomain} 2>/dev/null); do`,
        `  iptables -A OUTPUT -d "$ip" -p tcp --dport 443 -j ACCEPT`,
        `done`,
        ``,
      )
    })

    if (risk.networkPolicy.vpcOnly) {
      lines.push(
        `# ============================================`,
        `# VPC-only mode: allow internal RFC1918 ranges`,
        `# ============================================`,
        `iptables -A OUTPUT -d 10.0.0.0/8 -j ACCEPT`,
        `iptables -A OUTPUT -d 172.16.0.0/12 -j ACCEPT`,
        `iptables -A OUTPUT -d 192.168.0.0/16 -j ACCEPT`,
        ``,
      )
    }
  }

  lines.push(
    `# ============================================`,
    `# Logging`,
    `# ============================================`,
    `iptables -A OUTPUT -j LOG --log-prefix "[ClaudeGuard-BLOCKED] " --log-level 4`,
    ``,
    `echo "[ClaudeGuard] Firewall initialized. Policy: ${risk.networkPolicy.defaultEgress} outbound."`,
    `echo "[ClaudeGuard] Allowed domains: ${allowAll ? 'ALL (standard)' : allDomains.size + ' domains'}"`,
    ``,
    `# Hand off to the container's CMD`,
    `exec "$@"`,
  )

  return {
    filename: 'init-firewall.sh',
    content: lines.join('\n'),
    language: 'bash',
    description: 'Container-level network policy with default-deny outbound and allowlisted domains',
  }
}
