import type { ConfigProfile } from '../../domain/entities/config-profile'
import { RISK_PROFILES } from '../../domain/value-objects/risk-profile'
import type { GeneratedArtifact } from '../../domain/ports/template-engine-port'

export function generatePreToolUseHook(profile: ConfigProfile): GeneratedArtifact {
  const risk = RISK_PROFILES[profile.riskProfile]
  const isParanoid = profile.riskProfile === 'paranoid'

  const content = `#!/bin/bash
# ClaudeGuard Pre-Tool-Use Hook
# Risk Profile: ${risk.name}
# Runs BEFORE every Claude Code tool invocation
# Generated by ClaudeGuard Security Configurator

set -euo pipefail

TOOL_NAME="\${CLAUDE_TOOL_NAME:-unknown}"
TOOL_INPUT="\${CLAUDE_TOOL_INPUT:-}"
TIMESTAMP="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
LOG_FILE="/tmp/claudeguard-audit.log"

# ============================================
# Audit logging
# ============================================
echo "{\\"timestamp\\":\\"\${TIMESTAMP}\\",\\"event\\":\\"pre-tool-use\\",\\"tool\\":\\"\${TOOL_NAME}\\",\\"input_preview\\":\\"\${TOOL_INPUT:0:200}\\"}" >> "\${LOG_FILE}"

# ============================================
# Dangerous command detection
# ============================================
if [ "\${TOOL_NAME}" = "Bash" ]; then
  COMMAND="\${TOOL_INPUT}"

  # Block known-dangerous patterns
  DANGEROUS_PATTERNS=(
    "rm -rf /"
    "rm -rf /*"
    "mkfs"
    "dd if="
    ":(){:|:&};:"
    "chmod -R 777"
    "shutdown"
    "reboot"
    "halt"
    "poweroff"
  )

  for pattern in "\${DANGEROUS_PATTERNS[@]}"; do
    if echo "\${COMMAND}" | grep -qF "\${pattern}"; then
      echo "[ClaudeGuard] BLOCKED: Dangerous command detected: \${pattern}" >&2
      echo "{\\"timestamp\\":\\"\${TIMESTAMP}\\",\\"event\\":\\"blocked\\",\\"reason\\":\\"dangerous_command\\",\\"pattern\\":\\"\${pattern}\\"}" >> "\${LOG_FILE}"
      exit 1
    fi
  done
${isParanoid ? `
  # Paranoid mode: block ALL direct bash execution
  echo "[ClaudeGuard] BLOCKED: Direct Bash execution is disabled in Paranoid mode" >&2
  echo "{\\"timestamp\\":\\"\${TIMESTAMP}\\",\\"event\\":\\"blocked\\",\\"reason\\":\\"paranoid_no_bash\\"}" >> "\${LOG_FILE}"
  exit 1` : `
  # Block curl/wget piping (supply chain attack vector)
  if echo "\${COMMAND}" | grep -qE "(curl|wget).*\\|.*(bash|sh|python)"; then
    echo "[ClaudeGuard] BLOCKED: Remote code execution pattern detected" >&2
    echo "{\\"timestamp\\":\\"\${TIMESTAMP}\\",\\"event\\":\\"blocked\\",\\"reason\\":\\"remote_code_exec\\"}" >> "\${LOG_FILE}"
    exit 1
  fi`}
fi

# ============================================
# File path validation
# ============================================
if [ "\${TOOL_NAME}" = "Write" ] || [ "\${TOOL_NAME}" = "Edit" ]; then
  # Block writes to sensitive paths
  SENSITIVE_PATHS=(
    "/etc/"
    "/usr/"
    "/var/"
    "/root/"
    "/home/claudecode/.ssh/"
    "/home/claudecode/.env"
    ".env"
    ".env.local"
    "credentials"
    "secrets"
  )

  for path in "\${SENSITIVE_PATHS[@]}"; do
    if echo "\${TOOL_INPUT}" | grep -qF "\${path}"; then
      echo "[ClaudeGuard] BLOCKED: Write to sensitive path: \${path}" >&2
      echo "{\\"timestamp\\":\\"\${TIMESTAMP}\\",\\"event\\":\\"blocked\\",\\"reason\\":\\"sensitive_path\\",\\"path\\":\\"\${path}\\"}" >> "\${LOG_FILE}"
      exit 1
    fi
  done
fi

# Hook passed — allow execution
exit 0
`

  return {
    filename: 'hooks/pre-tool-use.sh',
    content,
    language: 'bash',
    description: 'Pre-execution validation hook: blocks dangerous commands, validates file paths, audit logs',
  }
}

export function generatePostToolUseHook(profile: ConfigProfile): GeneratedArtifact {
  const risk = RISK_PROFILES[profile.riskProfile]

  const content = `#!/bin/bash
# ClaudeGuard Post-Tool-Use Hook
# Risk Profile: ${risk.name}
# Runs AFTER every Claude Code tool invocation
# Generated by ClaudeGuard Security Configurator

set -euo pipefail

TOOL_NAME="\${CLAUDE_TOOL_NAME:-unknown}"
TOOL_OUTPUT="\${CLAUDE_TOOL_OUTPUT:-}"
TIMESTAMP="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
LOG_FILE="/tmp/claudeguard-audit.log"

# ============================================
# Audit logging
# ============================================
echo "{\\"timestamp\\":\\"\${TIMESTAMP}\\",\\"event\\":\\"post-tool-use\\",\\"tool\\":\\"\${TOOL_NAME}\\",\\"output_length\\":\${#TOOL_OUTPUT}}" >> "\${LOG_FILE}"

# ============================================
# Credential scanning
# ============================================
CREDENTIAL_PATTERNS=(
  "AKIA[0-9A-Z]{16}"                          # AWS Access Key
  "AIza[0-9A-Za-z_-]{35}"                     # Google API Key
  "sk-[a-zA-Z0-9]{48}"                        # Anthropic/OpenAI API Key
  "ghp_[a-zA-Z0-9]{36}"                       # GitHub Personal Access Token
  "glpat-[a-zA-Z0-9_-]{20}"                   # GitLab Personal Access Token
  "xox[bprs]-[0-9a-zA-Z]{10,}"               # Slack Token
  "-----BEGIN (RSA |EC )?PRIVATE KEY-----"     # Private Keys
  "mongodb(\\+srv)?://[^\\s]+"                  # MongoDB Connection String
  "postgres://[^\\s]+"                          # PostgreSQL Connection String
)

for pattern in "\${CREDENTIAL_PATTERNS[@]}"; do
  if echo "\${TOOL_OUTPUT}" | grep -qE "\${pattern}"; then
    echo "[ClaudeGuard] WARNING: Credential-like pattern detected in tool output" >&2
    echo "{\\"timestamp\\":\\"\${TIMESTAMP}\\",\\"event\\":\\"credential_detected\\",\\"tool\\":\\"\${TOOL_NAME}\\",\\"pattern_type\\":\\"redacted\\"}" >> "\${LOG_FILE}"

    # In Strict/Paranoid mode, block the output
    ${profile.riskProfile !== 'standard' ? `echo "[ClaudeGuard] BLOCKED: Credential exposure in ${risk.name} mode" >&2
    exit 2` : `echo "[ClaudeGuard] Credential detected — logged for review" >&2`}
  fi
done

# Hook passed
exit 0
`

  return {
    filename: 'hooks/post-tool-use.sh',
    content,
    language: 'bash',
    description: 'Post-execution hook: credential scanning, audit logging, output validation',
  }
}
